### ISSUE TITLE
Log when a relay fails to parse

### ISSUE THREAD

**Issue by ralexstokes** [ralexstokes/mev-rs#102]
Relays must be provided in a particular configuration and if this fails for some reason the entry is silently discarded:

https://github.com/ralexstokes/mev-rs/blob/6f5bcb6ed8c2e4100f746ed15e6127ab04fa3f96/mev-boost-rs/src/service.rs#L56-L65

instead, we should log a warning when one relay fails to parse

**Comment by chirag-bgh** [comment]
I will take this.
