### ISSUE TITLE
support `deneb` in `mev-boost-rs`

### ISSUE THREAD

**Issue by ralexstokes** [ralexstokes/mev-rs#137]
we should verify `mev-boost-rs` follows the latest specs for `deneb`.

adding support for the fork will mostly come down to ensure we can parse the correct types here: https://github.com/ralexstokes/mev-rs/blob/main/mev-rs/src/blinded_block_provider/api/client.rs

and that they follow the `builder-specs` APIs here: https://ethereum.github.io/builder-specs/?urls.primaryName=dev#/Builder

**Comment by samtvlabs** [comment]
I want to clarify what needs to be done here. It appears alot of the work to support [deneb](https://github.com/ralexstokes/mev-rs/blob/main/mev-rs/src/types/deneb.rs) is already . However looking at the [specs](https://github.com/ethereum/consensus-specs/blob/dev/specs/deneb/beacon-chain.md), it would appear that some values like [this](https://github.com/ethereum/consensus-specs/blob/dev/specs/deneb/beacon-chain.md#validator-cycle) are missing. Looking at the code , it would appear that the place to implement these are in [ethereum-consensus  ](https://github.com/ralexstokes/ethereum-consensus)

**Comment by ralexstokes** [comment]
yes, it looks like we are good to go, thanks for checking!
