### ISSUE TITLE
Don't leak signature error during relay verification

### ISSUE THREAD

**Issue by ralexstokes** [ralexstokes/mev-rs#210]
https://github.com/ralexstokes/mev-rs/blob/4469676ce10eb023bb5478e88429aaed84fbf619/mev-relay-rs/src/relay.rs#L535

This check was added in #208 but leaks the underlying error to the caller if there is a problem.

For security reasons, it is better to return an opaque "failure" error. Note that we still want to log the error locally. Reference the pattern elsewhere like here: https://github.com/ralexstokes/mev-rs/blob/main/mev-relay-rs/src/relay.rs#L529-L532

Let's update this to check for the `Err` variant, `warn!` about the bad signature, but only return `RelayError::InvalidSignedBlindedBeaconBlock` to the caller

**Comment by EchoAlice** [comment]
Does `verify_blinded_block_signature()` need to return a `RelayError` internally too?
