### ISSUE TITLE
Drop use of `async_trait` in `mev-rs` crate?

### ISSUE THREAD

**Issue by ralexstokes** [ralexstokes/mev-rs#218]
There are some traits in `mev-rs` that have async methods, and the way to implement this until recently has been with the use of the `async_trait` crate.

[As of Rust 1.75](https://blog.rust-lang.org/2023/12/21/async-fn-rpit-in-traits.html), there is preliminary support for using `async` methods in a trait and I wonder if there is enough native support to drop `async_trait`.

**Comment by sarmatdev** [comment]
`async_trait` is required by `axum`

<img width="1779" alt="Screenshot 2024-05-18 at 18 44 05" src="https://github.com/ralexstokes/mev-rs/assets/58251349/bd258a60-7bf7-4aba-8bc1-374f810cdf15">

**Comment by ralexstokes** [comment]
thanks for looking into this!

it doesn't seem to be necessarily required by `axum` but `async-trait` gives additional trait bounds that do satisfy `axum::Handler` -- if you look at the blog post above, they talk about this

I think for now, we just table this
