### ISSUE TITLE
refactor a component to handle `ValidatorRegistrations`

### ISSUE THREAD

**Issue by ralexstokes** [ralexstokes/mev-rs#33]
#32 introduces (validated) validator registrations to a builder who trusts they are valid (due to the current tight coupling of the two components).

we will eventually want to make a builder that does not make this assumption and that means needing to handle validation of any incoming registrations and tracking them (keying by `public_key` seems nice so far).

this functionality is implemented in the `relay` right now and it would be nice to refactor into a re-usable `ValidatorRegistrar` or something component so that this logic can be shared in multiple places.

this component could also contain the "mempool" functionality, see #28.

**Comment by leruaa** [comment]
@ralexstokes As you can see in the PR above, I started to work on this issue: For now I just extracted validate_registration() and dependants methods from relay to a newly created `ValidatorRegistrar` struct. Can you have a small look and tell me if I'm heading in the wrong direction?

**Comment by ralexstokes** [comment]
Fixed in #70
