### ISSUE TITLE
cannot run mock/example relay

### ISSUE THREAD

**Issue by sourdzl** [ralexstokes/mev-rs#37]
hi, i'm just trying to get setup for the first time and running

`cargo run relay mock example.config.toml`

which results in

```
Error: could not parse TOML

Caused by:
    missing field `beacon_node_url` for key `relay` at line 8 column 1
```

wasn't sure what to put here - can you provide an example value?  

if i'm running an a local beacon chain i guess something like `127.0.0.1:5052` would make sense, but then i got 

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: RelativeUrlWithoutBase', mev-relay-rs/src/service.rs:37:60
```

**Comment by ralexstokes** [comment]
ah sorry! 

I have not updated the example.

I will update today and see if I can add some kind of test to ensure there is no further regression.
