### ISSUE TITLE
Publish new release with vendored `libssl`

### ISSUE THREAD

**Issue by paulhauner** [ralexstokes/mev-rs#42]
Over in https://github.com/ralexstokes/beacon-api-client/pull/29 I've removed the dependency on `libssl.so.1.1`. It would be much appreciated if there could be a new release without that dependency. That would help me with some devops things I'm working on.

I appreciate that your release schedule doesn't revolve around me though, so no worries if you'd like to do it later :relaxed:

**Comment by paulhauner** [comment]
Oh also, thanks for creating and maintaining this repo! :heart:

**Comment by ralexstokes** [comment]
I'll go make one now :)

**Comment by ralexstokes** [comment]
so I don't think we need a new release?

the use of `beacon-api-client` is not pinned to a particular commit/tag so as soon as `cargo` notices the dep has updated you should be good to go...

if you need to force an update I usually do `cargo update -p beacon-api-client`

**Comment by paulhauner** [comment]
I was hoping to pull the binary from the release page, but it's no problem if that's a big deal!

**Comment by ralexstokes** [comment]
@paulhauner https://github.com/ralexstokes/mev-rs/releases/tag/v0.2.1

:)
