### ISSUE TITLE
tie break builder bids by block hash

### ISSUE THREAD

**Issue by ralexstokes** [ralexstokes/mev-rs#8]
this is a bit of an edge case but in the event that multiple bids come back with the *same value* but are for different payloads, then the mux should select an execution block randomly, e.g. tie break w/ the execution block hash

**Comment by ralexstokes** [comment]
currently the policy is:

```
        // for now, break any ties by picking the first bid,
        // which currently corresponds to the fastest relay
```

**Comment by ameya-deshmukh** [comment]
@ralexstokes is this still open? Would love to give it a shot

**Comment by ralexstokes** [comment]
@ameya-deshmukh yes! please open a PR :)

should be a fairly self-contained and scoped change to bid selection in `mev-boost-rs`
