### ISSUE TITLE
support the flashbots relay URL scheme

### ISSUE THREAD

**Issue by ralexstokes** [ralexstokes/mev-rs#82]
`mev-boost-rs` does check the signature on `SignedBuilderBid`s however it just accepts a valid signature from any public key in the bid.

`mev-boost` requires a public key for each connected relay like `https://0xpublic-key@some-relay.com` and presumably checks the public keys match on each bid.

let's verify the `mev-boost` behavior and if it makes sense copy this over to `mev-boost-rs`
edit: update: it does https://github.com/flashbots/mev-boost/blob/main/server/service.go#L358, so let's go ahead and do this in `mev-boost-rs`

**Comment by ralexstokes** [comment]
to fix this, I'd extend the definition of `Relay` here: https://github.com/ralexstokes/mev-rs/blob/9cf2207dcc629f1b9e2bbc58e070bbc5924e0e51/mev-boost-rs/src/relay_mux.rs#L8 (so indirectly here: https://github.com/ralexstokes/mev-rs/blob/9cf2207dcc629f1b9e2bbc58e070bbc5924e0e51/mev-rs/src/blinded_block_provider/api/client.rs#L18) to also try to parse a hex-string from the host like the above format.

then when calling `validate_bid` here: https://github.com/ralexstokes/mev-rs/blob/9cf2207dcc629f1b9e2bbc58e070bbc5924e0e51/mev-boost-rs/src/relay_mux.rs#L115, we can grab the relay's public key (e.g. `&self.relays[relay_index].public_key`) or something

**Comment by haythemsellami** [comment]
Will try to do this :D
